### ISSUE TITLE
Adjust tree view if null database (spark)

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-docs#104]
On Spark, where `database` is always `null`, the `Database` tree view looks like:

<img width="306" alt="Screen Shot 2020-06-22 at 10 41 57 AM" src="https://user-images.githubusercontent.com/13897643/85300809-0833b080-b475-11ea-8cb5-4639eaf83f8c.png">

Suggestions from @dallyhorton, who initially surfaced this [in Slack](https://getdbt.slack.com/archives/C2JRRQDTL/p1592790227278400):

> I would suggest just using the name of the project in place of the null. Better still, do we need a root node? It just mean one less click to expand the list of schemas. If we need the root node, could we default the tree to expanded (instead of collapsed)?

**Comment by mark-dessain-maersk** [comment]
Had the same issue and was pointed in this direction. Not had time to look at the underlying code but a quick fix / workaround is to run the following after generating the documentation:

```bash
sed 's/"database": null/"database": "<DATABASE_NAME>"/g' ./target/manifest.json
```

**Comment by markdessain** [comment]
Had the same issue and was pointed in this direction. Not had time to look at the underlying code but a quick fix / workaround is to run the following after generating the documentation:

```bash
sed 's/"database": null/"database": "<DATABASE_NAME>"/g' ./target/manifest.json
```
