### ISSUE TITLE
Add the ability to embed DAG (or other parts) in other sites

### ISSUE THREAD

**Issue by tayloramurphy** [dbt-labs/dbt-docs#110]
Our specific use case is around embedding the DAG for a given model into our handbook somewhere. Instead of a link to the dbt docs, I'd like them to see the actual DBT dag, probably with filters in place (`+`, `@`, etc.) to see the lineage of a fact table.

**Comment by drewbanin** [comment]
heck yeah, I love the idea of making reusable React components that are node-selection aware. I think some obvious use-cases include:
 - on docs.getdbt.com to augment technical documentation
 - embedded use-cases like the one you described

I'm kind of picturing a suite of components like this which can be used together from a shared data model (think: ERDs).

Can you just provide some context around what embedding into your handbook would require? Do you think a React component would work, or would you need something more like an iframe?

**Comment by tayloramurphy** [comment]
@drewbanin most of our embeddings are via iframes I believe. The handbook is a static site, so I don't think a react component would work. See https://about.gitlab.com/handbook/people-group/people-success-performance-indicators/#offer-acceptance-rate for an example

**Comment by dweaver33** [comment]
I know this is an old thread, but has anyone successfully done this?  I'd love to embed the DAG into Notion and other external sites.

**Comment by Gregory108** [comment]
Still desired
