### ISSUE TITLE
Handle percent encoding in some urls

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-docs#12]
Via the GitLab folks, it looks like in some cases, the docs site will render out a percent-encoded value instead of a hash character. This borks the pageload.

Example URL:
https://gitlab-data.gitlab.io/analytics/dbt/snowflake/#!/model/model.gitlab_snowflake.sfdc_opportunity%23sql

**Comment by mepa** [comment]
We run into similar when clicking a link to our internal dbt docs site hosted on GitHub pages.

Example URL: https://verbose-parakeet-6627b867.pages.github.io/#!/model/model.overhaul_sensors.fct_valid_shipment_logistics%23code

The docs were generated with `dbt-core==1.0.0`
