### ISSUE TITLE
Import missing source descriptions in documentation (table and columns) from catalog

### ISSUE THREAD

**Issue by fabrice-etanchaud** [dbt-labs/dbt-docs#128]
### Describe the feature

In the generated documentation, populate source table and columns description from catalog.

### Additional context

From what I see, these comments are already in the catalog.json file.

### Who will this benefit?

All users with well documented source data.

### Are you interested in contributing this feature?

I did not try to circonvent the code impacted, my python is too poor, but my jinja is rich, so why not ?

**Comment by fabrice-etanchaud** [comment]
By the way, @jtcohen6 , were you kidding when you said you envisioned to move to France ? I truly think dbt has a great potential in Europe these next years !

**Comment by jtcohen6** [comment]
Not kidding!

**Comment by fabrice-etanchaud** [comment]
Great ! Do not hesite in contacting me (but I think you already have acquaintances in France to envision such a change !) when the decision is taken ! By the way, dbt has potential all around the world ;-) so you have the choice !
