### ISSUE TITLE
Custom Logos

### ISSUE THREAD

**Issue by Mr-Nobody99** [dbt-labs/dbt-docs#141]
### Describe the feature
It would be nice if users had the ability to add a custom logo to the docs site. For example if the user had an image file that is placed in the target folder it would be used either along side or in place of the dbt logo.

### Describe alternatives you've considered
this can be done manually but that does not seem like a practical solution.

### Additional context
N/A

### Who will this benefit?
Anyone using dbt who has a brand or logo.

### Are you interested in contributing this feature?
Yes, I would like to contribute this feature.

**Comment by akmalsoliev** [comment]
Any update on this issue?

**Comment by dbeatty10** [comment]
Closing as a duplicate of https://github.com/dbt-labs/dbt-docs/issues/50
