### ISSUE TITLE
Display `enabled: true | false` on each model page

### ISSUE THREAD

**Issue by haleemur** [dbt-labs/dbt-docs#154]
### Describe the feature

Would love to see whether a model is `enabled: true` on the the models' page. A model could be disabled either in the `dbt_project.yml` file or on the `model_file.sql`. I think a good place to display this information is in the `Detail` section of the model, next to `tags` & `package`. Perhaps even highlight it green vs red for (enabled vs disabled). 

### Describe alternatives you've considered

Currently, the only way to show this information in the documentation is by placing the `enabled: false` in the `config` at the top of the file, and assuming `enabled: true` otherwise. This is not ideal since it is possible (and IMO ergonomic) to use the `dbt_project.yml` file to control this behavior. Additionally, even if we adhere to specifying `enabled: false` in each model individually, the documentation is geared towards business user who might not know enough sql / jinja / dbt to understand the significance of `enabled: false` or may not browse below the fold to see the sql snippet.

### Who will this benefit?
This will help improve end users ability to discover what is set up & should be fresh, and what artefact may be unsupported currently

### Are you interested in contributing this feature?
Would love to contribute, but I'm patently bad at javascript & front-end stuff. If this is a new-comer friendly feature, I would greatly appreciate some pointers on where to start looking.

**Comment by jtcohen6** [comment]
Hey @haleemur, fair point—I'd like to get to a place where we can start surfacing more configurations in the dbt-docs to benefit data modelers who use it as a way to quickly understand what's going on in the project.

In the case of `enabled: false`, however, I don't believe that disabled models should show up in the docs site at all! Is that something you've seen?

**Comment by haleemur** [comment]
Hi @jtcohen6, sorry about that. I guess I got confused in switching branches, generating & checking out the docs. 

I now think the first issue is to decide whether to change behaviour and display disabled models. 

A disabled model would still leave behind the table / view artefact in the database, and downstream users might still be pointing to it. Having the model show up in the docs with a different background color & big warning signs would be useful in communication.
