### ISSUE TITLE
Git clone application not runnable

### ISSUE THREAD

**Issue by rdnscr** [dbt-labs/dbt-docs#160]
### Describe the bug
I just downloaded the repo and tried to run it. I always get from the webpack build following exceptions:
https://github.com/fishtown-analytics/dbt-docs
ERROR in ./src/app/components/graph/graph-launcher.html 2:0
Module parse failed: Unexpected token (2:0)

It seesm that the loaders for html are not working as expected. I did a fresh npm install (which will pull latest versions) since a package-lock.json is missing. In addition i have nod 14.x running

### Steps To Reproduce
Clone and try to run it

### Expected behavior
Webpack build should work after a clean clone and npm install

Any help is appreciated.

**Comment by jtcohen6** [comment]
Hey @rdnscr, did you go through all the steps outlined in the readme under [Development](https://github.com/fishtown-analytics/dbt-docs#development)?

**Comment by rdnscr** [comment]
Yes i did all this steps:
### Development

After cloning this repository, run:

```bash
git submodule update --init --recursive
```

Then, install yarn and webpack.

```bash
npm install -g yarn webpack webpack-cli
```

You'll also need to install bundler if you don't already have it:
```bash
gem install bundler
bundle install
```

### Build / Run

To build the css files required for webpack:

```bash
cd styles
bundle exec jekyll build
cd -
```


To build an index.html file:

```bash
yarn install
webpack
```

And the webpack build failes. With the reason, that there is no proper loader registered for the html file. Here the first error occuring:

ERROR in ./src/app/overview/overview.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <div class="app-details app-scroll app-pad">
|     <app-scroll div class="app-frame app-pad">
|         <div class="panel panel-default">
 @ ./src/app/index.routes.js 6:14-49
 @ ./src/app/index.run.js
