### ISSUE TITLE
Add last updated date to dbt docs

### ISSUE THREAD

**Issue by emilieschario** [dbt-labs/dbt-docs#163]
### Feature description
Running dbt and deploying updated dbt docs may happen at the same time, but they also might not. One might fail, but the other might night. 

It would be great if it were explicit on the dbt docs site when they were last updated (for example the time that the last `dbt docs serve` was run. 

Current dbt home page
<img width="1424" alt="Screen Shot 2019-04-12 at 10 40 26 AM" src="https://user-images.githubusercontent.com/14057155/56056018-e8044f80-5d0f-11e9-98ec-ffd59e5f4b63.png">

Proposed 
![docs last updated_ 2019-04-12](https://user-images.githubusercontent.com/14057155/56056032-efc3f400-5d0f-11e9-97a0-b408c7bd23c9.png)

### Who will this benefit?
Anyone consuming docs.

**Comment by mrshu** [comment]
@jtcohen6 Would you be up for receiving a pull request with a sample implementation?

This turns out to be something we miss in our deployment.

Thanks!

**Comment by jtcohen6** [comment]
@mrshu Surely, I'd welcome that! What are you thinking in terms of:
- where in the docs page this should be displayed
- whether to display one or both of the `generated_at` values from `manifest` + `catalog`

**Comment by mrshu** [comment]
Thanks @jtcohen6 !

As for where to display this on the docs page, I believe the best place would be the lower part of the menu bar on the left.

I believe displaying both `generated_at` valued would be probably the best way to go forward at this point -- any other option may cause unnecessary confusion as @beckjake mentioned.

I see if I can put something like this together and will let you know.

Thanks!

**Comment by mrshu** [comment]
@jtcohen6 Well, turns out I was not able to put something together rather quickly :slightly_smiling_face: 

Has anything changed on the `dbt` side that would be relevant for something like this? In any way I look at this, we are sorely missing this in the way we use `dbt`, so I'd like to get back to this sooner or later.

Thanks!

**Comment by jtcohen6** [comment]
Nothing has changed from dbt-core's perspective here: `metadata.generated_at` is available in both the [manifest](https://schemas.getdbt.com/dbt/manifest/v3/index.html#metadata_generated_at) and the [catalog](https://schemas.getdbt.com/dbt/catalog/v1/index.html#metadata_generated_at).

I think the change here would be quite self-contained. If you're able to contribute it, one of us can take a look at the PR, and make sure it's included in the docs site that ships with the next version of dbt-core.
