### ISSUE TITLE
Broken DAG dependency filter issue for exposure names that contain spaces

### ISSUE THREAD

**Issue by aaronsteers** [dbt-labs/dbt-docs#168]
### Describe the bug

While testing the new `exposures` feature in `dbt docs`, I found that the [example](https://docs.getdbt.com/docs/building-a-dbt-project/exposures/) in the dbt documentation uses an exposure name which contains spaces. However, when viewing the docs for a site that does contain spaces in an exposure name, this breaks the filter feature in the bottom pane of the full screen DAG view, as well as the right-hand inline version of the DAG on the exposure's dedicated page.

Replacing spaces with underscores resolves the issue.

### Steps To Reproduce

1. Create an exposure whose name contains spaces.
2. Run `dbt docs generate && dbt docs serve`
3. Navigate to the full screen DAG view and confirm that the exposure is listed correctly (also in orange). (WORKS. ✅)
4. Select the node and attempt to focus on that node. (Note that all other nodes disappear and upstream nodes are not correct. ❌)
5. Navigate to the exposures dedicated page and expand the right-hand inline DAG view. (Note that no upstream nodes appear, even though there were upstream nodes identified in the initial unfiltered DAG view.)

### Expected behavior

Either exposure names should not allow spaces or the `dbt docs` rendering backend should correctly escape or quote the name to ensure upstreams are correctly rendered when the exposure is filtered upon.

### Screenshots and log output

n/a

**The output of `dbt --version`:**

```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - postgres: 0.18.1
  - redshift: 0.18.1
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - ```

### Additional context

n/a

**Comment by jtcohen6** [comment]
You're right, dbt will not raise an error today if you define an exposure name that contains spaces, but some things (like the dbt-docs DAG viz) will definitely not work as intended. This is actually true of most resource types today—did you know that model file names can contain spaces, too, and will by default create views/tables with spaces in their identifiers?

I think the most likely outcome is that we remove support for spaces in exposure names (https://github.com/fishtown-analytics/dbt/issues/2970).

> I found that the [example](https://docs.getdbt.com/docs/building-a-dbt-project/exposures/) in the dbt documentation uses an exposure name which contains spaces.

If so, we should definitely change this. I can't find the exposure name you're referencing, though; where are you seeing it?

**Comment by troyel** [comment]
@jtcohen6  : we had the same issue today as we want to display PBI report documentation and lineage to end-users. If supporting exposure names with spaces is out of the question, what about a different field for exposure display name or something similar?

**Comment by jtcohen6** [comment]
Adding an optional display name makes a lot of sense to me! Perhaps we should call it `label`, for consistency with the [brand-new `metrics` definitions](https://next.docs.getdbt.com/docs/building-a-dbt-project/metrics)?

**Comment by troyel** [comment]
That sounds great @jtcohen6 ! :-)
