### ISSUE TITLE
Slow response times interacting with data lineage chart on large projects

### ISSUE THREAD

**Issue by vogt4nick** [dbt-labs/dbt-docs#170]
### Describe the bug

Users open the data lineage graph by clicking the button at the bottom-right corner of the page. It takes 2-3 seconds for the graph to load. This issue persists beyond the initial load too. Most interactions take 2-3 seconds to complete when several nodes are selected in the lineage graph. Response times are also slow when using selectors; the page becomes briefly unresponsive and keystrokes aren't immediately input to the text field.

### Steps To Reproduce

Serve the data catalog for a large dbt project with relatively large `manifest.json` and `catalog.json` files; in my example,  300+ models and 1800+ tests generate a 6.2 MB `manifest.json` and a 1.2 MB `catalog.json`. 

Click the "data lineage chart" button on the bottom-right corner of the page. 

See profiling output below for benchmark.

### Expected behavior

The data lineage chart should load under 500ms (or some other arbitrary threshold determined by users' tolerance).

### Screenshots and log output

The "View Lineage Chart" button:

![image](https://user-images.githubusercontent.com/31822672/105382555-2fef2080-5bde-11eb-8b41-df6de9dfcbfc.png)

My profiling output:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/31822672/105382410-0930ea00-5bde-11eb-868a-0665333bcec9.png">

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.18.0
  - snowflake: 0.18.0
  - redshift: 0.18.0
  - postgres: 0.18.0
```

**The operating system you're using:** 

The data catalog is served with the base Docker image [library/nginx:1.19.0-alpine](https://hub.docker.com/layers/nginx/library/nginx/1.19.0-alpine/images/sha256-2fa12030ffb0224e0b2e17bc4b1f1479e191e2fd65869fc60d09a8efa5b6d879?context=explore).

The documentation is generated with the base Docker image [library/python:3.7.7-slim-buster](https://hub.docker.com/layers/python/library/python/3.7.7-slim-buster/images/sha256-f9bfca3b8272320ac851918e69be5e384087f87b313c56fbb2eb3c8384dc1e50?context=explore).

**The output of `python --version`:** 3.7.7

**Comment by kevnoo** [comment]
I'm not sure where this issue currently stands but @vogt4nick, @drewbanin and @jtcohen6 - we (kraftheinz engineering) are just about wrapped up with converting dbt docs over to React. One of the first things we did was compressed the manifest.json file during the build which solved all of the performance issues. For context, we currently have over 115 projects and the site loads in less than 5 seconds after that change.

We will have a repo to share with everyone once we are done packaging it up for public consumption.

**Comment by jtcohen6** [comment]
@kevnoo Very cool!! I'd love to see, when it's ready to share

**Comment by drewbanin** [comment]
super cool and very exciting to hear @kevnoo! Anything we can help out with?

Also - wondering if you're thinking about upstreaming these changes. Did you rebuild the site from scratch, or does it look like a branch off of the existing docs site? Would love to hear more if you're able to share!

**Comment by kevnoo** [comment]
We are very close to publishing the code but would be open to chatting directly prior to (or after).

The site itself looks exactly the same (for the most part). We are using the manifest.json but do not use the catalog.json or run_results.json. The reason for this is because we have also integrated it directly with Snowflake via a backend API. We also had some issues with the catalog.json due to the way we have implemented DBT across all of our projects. 

The biggest change was a massive revamp to the lineage graph - this is all done now using HTML Canvas. 

As for upstreaming the changes, there would be some work required to have it act just like the existing version. We have not gone through the process to allow it to be part of the dbt docs generate process - this is something we are definitely open to but would need some guidance on. And obviously there would need to be a version that does include the use of run_results and catalog. These are all things we agree with and would be open to helping out on but as of now can't prioritize it due to a lack of time.

**Comment by ajbosco** [comment]
@kevnoo any update on if/when you'll be publishing the React version of dbt docs?

**Comment by kevnoo** [comment]
Hey @ajbosco - sorry for the delay! It's ready.  @AlexanderKutz is going to work on publishing it over the next couple days.

**Comment by Mr-Nobody99** [comment]
Hello @ajbosco and anyone else interested in checking it out, I have published the react version [here](https://github.com/Mr-Nobody99/react-dbt-docs)

**Comment by saraleon1** [comment]
+1 dbt Cloud user - the slow response time of the data lineage chart for their larger project made this feature relatively unusable. Any time they tried to move or modify the chart, it lags and takes a few seconds to load correctly again

**Comment by StepienTomasz** [comment]
+1. The page crashes with our large DBT repo when interacting with the lineage chart.
Here are some number for reference. 
```
Found 1042 models, 1071 tests, 0 snapshots, 0 analyses, 493 macros, 0 operations, 29 seed files, 650 sources, 10 exposures, 0 metrics
```
![image](https://user-images.githubusercontent.com/91733988/227967675-ef365ffa-b078-4e3e-aa9e-e1a3ebd91c51.png)

**Comment by sfc-gh-kumaurya** [comment]
I am also facing the same issue as mentioned by @StepienTomasz while loading the lineage graphs for the "sources". We are getting the page unresponsive and it loads after 3-4 minutes.

**Comment by jaredx435k2d0** [comment]
Agreed it is very slow and causes a really poor user experience.

Would love to see this move forward! We're evangelizing dbt at the org and the docs are a large part of that.

**Comment by sungchun12** [comment]
FYI on what a full rewrite can look and feel like for dbt docs: https://dagster.io/blog/dbt-docs-on-react

**Comment by sungchun12** [comment]
@nobgb no updates as I believe official dbt docs development will go through dbt Cloud only. I'll let the dbt maintainers speak to it more!

**Comment by nobgb** [comment]
couldn't find the info about it in dbt docs. Would you be so kind to share those with me, i'd like to follow that
