### ISSUE TITLE
Docs unexpectedly shows an item for `dbt_postgres` when using a Redshift profile

### ISSUE THREAD

**Issue by eiof** [dbt-labs/dbt-docs#171]
### Describe the bug

`dbt_postgres` is an item under **Projects** when using a Redshift profile. Is this expected?

### Steps To Reproduce

You can reproduce this using the [jaffle_shop](https://github.com/fishtown-analytics/jaffle_shop) project. Update `dbt_project.yml` to use a Redshift profile.

Run `dbt docs serve`, and you'll see a `dbt_postgres`.

### Expected behavior

It looks like [`dbt_postgres` contains adapter macros](https://github.com/fishtown-analytics/dbt/tree/dev/margaret-mead/plugins/postgres/dbt/include/postgres). From my conversations with dbt maintainers, I think docs typically excludes adapter nodes from dbt docs. I'd expect `dbt_postgres` to be excluded. From what I know, the Redshift adapter macros reference some Postgres macros, which might explain why `dbt_postgres` has any relevance here.

For what it's worth, if a Postgres profile is used, docs does not show an item for `dbt_postgres`.

### Screenshots and log output

<img width="310" alt="Screen Shot 2021-01-26 at 2 37 15 PM" src="https://user-images.githubusercontent.com/4501220/105896761-3c5fe880-5fe5-11eb-9282-5b5d18809600.png">

**The output(s) of `dbt --version`:**
```
0.18.1
0.19.0rc2
```

**Comment by kwigley** [comment]
Leaving behind some breadcrumbs, I think this is the snippet in question that results in this behavior.
https://github.com/fishtown-analytics/dbt-docs/blob/97570c58c474dfbba0b145576792bc8e3ead6c5c/src/app/services/project_service.js#L309-L315
