### ISSUE TITLE
Ability to hide Project tree in sidebar and see only the Database tree

### ISSUE THREAD

**Issue by MarkMacArdle** [dbt-labs/dbt-docs#173]
### Describe the feature
The Project tree in the sidebar is good for people who work with dbt, but for those who don't it introduces a lot of dbt jargon (sources, models, macros etc). In my company the docs website will primarily be used by business users who will have no dbt experience and only be familiar with seeing the tables and schemas type view that the Database sidebar tree provides.

When creating the docs website a flag to hide or not create the Project tree would be useful. Eg 
```
dbt docs generate --database-tree-only
```

<img width="296" alt="Screenshot 2021-02-01 at 13 15 30" src="https://user-images.githubusercontent.com/26261732/106463646-98b48380-648f-11eb-8732-48364e262239.png">

### Describe alternatives you've considered
Just telling users that there's a database tree view they can use. Worry that occasional users would forget that though and seeing an unfamiliar view of things would discourage use of the site.
 
### Additional context
Have a lot of business users who'll only use the site occasionally. If I tried teaching them about dbt and its jargon I don't believe many would retain the information. Want the website to be as frictionless as possible for them.

### Who will this benefit?
Any non-dbt users of the website

### Are you interested in contributing this feature?
Yes! Would love to help but unclear on where to start.

**Comment by chrisluedtke** [comment]
Not an ideal solution, but you can accomplish this with some post-processing on `index.html`:

```python
with open("index.html", "r") as f:
    index = f.read()

# select "Database" tab by default
index = index.replace('{e.nav_selected="project"}', '{e.nav_selected="database"}')

# hide "Project" tab
index = index.replace('<div class="switch ">', '<div class="switch " hidden>')

open("index.html", "w+").write(index)
```

Should look something like:
![image](https://user-images.githubusercontent.com/20371880/117183420-28bedd80-ad9d-11eb-8df4-18ec358c353b.png)
