### ISSUE TITLE
Support relative links to model attributes in docs

### ISSUE THREAD

**Issue by one-data-cookie** [dbt-labs/dbt-docs#178]
Similar to [linking another model in a description](https://docs.getdbt.com/reference/resource-properties/description/#link-to-another-model-in-a-description), it would be great to have the ability to link a particular attribute from a model.

For instance,
```yml
description: "Filtering done based on [payment_id](#!/model/model.jaffle_shop.stg_stripe__payments#payment_id)"
```

could lead to: `http://127.0.0.1:8080/#!/model/model.jaffle_shop.stg_stripe__payments#payment_id`.

That would open the model's doc page and scroll directly to the given attribute in the _Columns_ section.

**Comment by one-data-cookie** [comment]
Thanks for transferring it and sorry about that, @clrcrl! I had both of the repos opened and posted it into the wrong one without noticing. 🙈

Any thoughts on how complex it is to get this built?

**Comment by one-data-cookie** [comment]
I still believe this will be worth exploring. 🙂

**Comment by jtcohen6** [comment]
I think there may be overlap with the column anchoring abilities proposed in https://github.com/dbt-labs/dbt-docs/issues/186 + https://github.com/dbt-labs/dbt-docs/issues/233
