### ISSUE TITLE
Show a list of all Tags on the documentation site

### ISSUE THREAD

**Issue by MuhdOvais** [dbt-labs/dbt-docs#18]
There is high probability that different members in a big team may be using similar tags. Like some maybe using `marketing` and some `mktg`.
It will be neat to get the list of all the tags being used within a team to double check, before someone creates a new one. 

This can be on the documentation site along with other information. As Drew suggested, it would be neat to show a list of tags, then click one to see all of the associated models.

==

**Comment by Dilshodproxet** [comment]
I want to get the list of tags too...
