### ISSUE TITLE
Anchor links for individual columns/attributes within model page

### ISSUE THREAD

**Issue by cjkaufmann** [dbt-labs/dbt-docs#186]
### Describe the feature
I would love the ability to link to a specific column of my dbt documentation from other areas of documentation. For example, how you have linked directly to a specific header in your documentation (how you can click the # here and link directly to this 'overview' header. 
![image](https://user-images.githubusercontent.com/67108397/115050392-b3e93980-9ea9-11eb-9be8-5c0f3cb93dd1.png)
I want this ability in our docs, for example, putting a link to go directly to `dsse_reporting_group` 
![image](https://user-images.githubusercontent.com/67108397/115049418-b39c6e80-9ea8-11eb-9754-7096bf378fc8.png)

### Describe alternatives you've considered
I've tried using HTML anchor links, but this definitely doesn't work within doc blocks. 
![image](https://user-images.githubusercontent.com/67108397/115049543-d890e180-9ea8-11eb-9896-6049b3eead21.png)

### Additional context
This would be very useful for folks who have documentation on exposures for their dashboards, reports, etc. Since you can link from the docs to the exposures, this would allow you to link directly to the dbt docs from those exposures, as well. So it would become full circle. 

### Who will this benefit?
Everyone who documents their tables/databases/exposures. 

### Are you interested in contributing this feature?
I'm not sure I could, but I will do anything I can to help.

**Comment by cjkaufmann** [comment]
I don't see how to make this not 'stale', but I'd still like it reviewed if possible!

**Comment by jtcohen6** [comment]
Hey @cjkaufmann, sorry about that! I just removed the `Stale` label.

For context, as the Core team grows, we're updating our strategies for maintaining our various open source repos. I know we haven't been as responsive to issues in this repo. We just haven't been able to prioritize much net-new development on `dbt-docs`, relative to higher-leverage work in `dbt-core`.

If this is something you or another community member would be interested in working on, I _think_ it might work to add an anchor in the column details, somewhere in this neck of the woods:

https://github.com/dbt-labs/dbt-docs/blob/00ab3e7cf2ebef03870b35f7a4d560248fb662d6/src/app/components/column_details/column_details.html#L26-L30

**Comment by busprint** [comment]
This would be a great addition to docs, so we can create internal links to other models or macros in the documentation of columns or models.

**Comment by jtcohen6** [comment]
I will reopen this one, and mark as `help_wanted` for an interested community contributor. This isn't something that we'll be able to prioritize ourselves.

**Comment by xinkent** [comment]
I have submitted a Pull Request #577 to implement this feature. I've added anchor links for columns as discussed. 
Please take a look when you have a chance!
