### ISSUE TITLE
Config Graph Object colors

### ISSUE THREAD

**Issue by bodegus** [dbt-labs/dbt-docs#190]
Showing source nodes as green versus blue is very useful in the doc site.  It would be very helpful if the node colors could be configured.

We use tests extensively - being able to color code tests and other test facets such as "unit/integration" as orange and "source tests" as purple, would make our DAG graph more usable

We also use different schemas for staging, loading, marts, etc - being able to color code a node by schema would also make the DAG visual more useful to consumers

I am interested in submitting these changes to the open source project instead of our own fork - is this enhancement of community interest?

**Comment by miloszbednarzak** [comment]
I'd love that feature in dbt-docs
