### ISSUE TITLE
show column tags in dbt docs

### ISSUE THREAD

**Issue by alla-bongard** [dbt-labs/dbt-docs#199]
### Describe the feature
Currently, column metadata that is available in dbt docs is `description`,  `tests`, etc.

![image](https://user-images.githubusercontent.com/73834516/124255748-ce3ac700-db2a-11eb-8332-ce07fe9a6937.png)

Would be great to include column `tags` too.

![image](https://user-images.githubusercontent.com/73834516/124255976-0e01ae80-db2b-11eb-8be7-5967712d4c46.png)

Making tags visible (and searchable) in the UI could make it easier to look for specific data assets.

**Comment by miike** [comment]
It looks like adding columns is reasonably easy to do but adding to search looks like it's significantly more complicated (I don't think search currently works on column tags - just table tags).
