### ISSUE TITLE
Lineage graph conveniece features

### ISSUE THREAD

**Issue by Gregory108** [dbt-labs/dbt-docs#209]
For me Lineage graph (LG) misses some features:
- save LG layout
  - Automatic LG is always too entangled and not informative. After each launch of docs or re-wiring of DAG I have to sort models manually (= is rote tedious work)
- export as a vector image, or, at least, as PNG with very-very high resolution
  - If DAG chain is lengthy and/or have long model names, it LG becomes useless, because names of models are not visible. 
- jump to a model's documentation or even to a model's file from LG
  - Just ultra cool=)

I believe anyone, who uses dbt in a team or wants to present DAGs to anyone.

**Comment by anthonymoquin** [comment]
I just discovered that you can dynamically customize the `dbt` Lineage Graph in Chrome via the Console in DevTools.

The key is that `dbt` instantiates the [Cytoscape.js](https://js.cytoscape.org/) graph object as the `window.graph` variable in the DOM.  So for example, in the Console you can run this to get an array of all the elements (nodes, edges, etc.) in the graph:

`window.graph.elements()`

I've written a Javascript function that generates a high-res PNG using the `window.graph.png()` function, and injects a "thumbnail" at the end of the visual controls at the bottom of the chart.  Then you can right-click on the thumbnail to save the image:

Just create a chart using whatever filters you want, and then execute this function definition in the Console:
```
function add_hi_res_png(scale=1) {
	var png_output = window.graph.png({full:true,scale:scale});
	var png_img = document.createElement("img");
	png_img.src = png_output;
	png_img.width=100;
	png_img.height=100;
	png_img.setAttribute('style', 'border:1px solid white;');
	document.querySelector('.launcher-window .fields').appendChild(png_img);
}
```
Then run:  `add_hi_res_png()` and look for the new thumbnail at the bottom of the chart.

You can pass in a "scale" number between 0 and 1 (the default is 1, but for very large graphs, sometimes won't be able to generate at `scale=1`, and you'll get an empty image.  So try `add_hi_res_png(.5)` or even `add_hi_res_png(0.05)`)

Here is the JPG version of that function:

```
function add_hi_res_jpg(scale=1) {
	var jpg_output = window.graph.jpg({full:true,scale:scale});
	var jpg_img = document.createElement("img");
	jpg_img.src = jpg_output;
	jpg_img.width=100;
	jpg_img.height=100;
	jpg_img.setAttribute('style', 'border:1px solid white;');
	document.querySelector('.launcher-window .fields').appendChild(jpg_img);
}

add_hi_res_png(.5)
```

You can do all sorts of other things with the graph -- you just have to explore all the functions in the documentation here:  https://js.cytoscape.org/#notation/functions

Some other examples:

Change the width of all the edges:
`window.graph.edges().style('width','15')`

Use a [different layout](https://js.cytoscape.org/#core/layout), e.g. [`concentric` circles](https://js.cytoscape.org/#layouts/concentric):
`l=window.graph.elements().sort((a,b)=>b.connectedEdges().size()-a.connectedEdges().size()).layout({name:'concentric'})`
Then `l.run()`  (You have to call "run" on the new `layout` object returned from the `layout()` function.)

Add a directional "V" arrow [halfway between all connected nodes](https://js.cytoscape.org/#style/edge-arrow):
`window.graph.edges().style({'mid-source-arrow-shape':'vee'})`

Obviously, any changes you make will get reset if you refresh the page.  And it's all kind of clunky to do this from the Console, but it's better than nothing!

Hope that helps,
-Anthony

**Comment by nitred** [comment]
I would upvote this issue and get it removed from stale. The lineage graph is quite entangled for large graphs. Quoting the original issue description:

> Automatic LG is always too entangled and not informative. After each launch of docs or re-wiring of DAG I have to sort models manually (= is rote tedious work)
