### ISSUE TITLE
[Feature] dbt Docs DAG visualisation should include (generic) test nodes

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-docs#220]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

This is beautiful, and makes it easy to reason about the selection of tests as first-class participants in the DAG, as well as the behaviour of `dbt build`. 
![image](https://user-images.githubusercontent.com/7335046/137835524-2078c994-4cd9-4dcf-be26-1d9c74ab78bc.png)

Tests should be allowed to appear in the DAG view in dbt Docs (probably off by default). 

### Who will this benefit?

- [People trying to get the best out of `dbt build`](https://getdbt.slack.com/archives/C2JRTGLLS/p1633962686096200)
- People trying to wean themselves off of [indirect test selection](https://github.com/dbt-labs/dbt-core/issues/4082#issuecomment-945467959)

### Are you interested in contributing this feature?

Nah 😞

**Comment by JC-Lightfold** [comment]
Would love this - hugely valuable for securing data estate at enterprise level. If this was an easy add, it would be high value for the effort @jtcohen6 @joellabes
