### ISSUE TITLE
Additions to metrics documentations

### ISSUE THREAD

**Issue by jschintz** [dbt-labs/dbt-docs#246]
### Describe the feature
Docs for metrics currently omits some useful fields.  'Label', 'type' &  'sql' 

### Describe alternatives you've considered
Using the manifest/catalogue file instead is an option to rebuild the docs.

### Who will this benefit?
Consumers of metrics looking at documentation

### Are you interested in contributing this feature?
Since I pay for dbt cloud, I'd prefer dbt to.

**Comment by antaradas94** [comment]
I also look forward to this feature. I had implemented metrics , but the dbt docs dont really display the type, label etc. i think it would be amazing if the dbt docs also had this feature to display more parameters.
