### ISSUE TITLE
[CT-221] [Feature] Add comment for table and column from the database when generating docs

### ISSUE THREAD

**Issue by Zoynels** [dbt-labs/dbt-docs#251]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently, dbt gets column types from the database. I think it will be good if dbt could also receive the table and column descriptions from the database if it already exists and is not written in a YAML file.

### Who will this benefit?

Everybody. Docs would be filled with additional information from the database.

**Comment by emmyoop** [comment]
This is currently being worked on over in #263.
