### ISSUE TITLE
ML Exposures show up in UI as 'Ml'

### ISSUE THREAD

**Issue by jonstacks** [dbt-labs/dbt-docs#256]
### Describe the bug

The UI shows 'MI' for ML exposures.

### Steps To Reproduce

When adding an exposure of `type: ml`, the UI shows this exposure as 'Ml' <---lowercase L

### Expected behavior

Expected to see `ML` in the sidebar

### Screenshots and log output

![image](https://user-images.githubusercontent.com/6900888/160753521-14965e94-3f0c-431c-a0c2-5b9d74fb62ce.png)

**The output of `dbt --version`:**
Used the sample project with latest install. Can also reproduce on `0.20.2`
```
installed version: 1.0.4
   latest version: 1.0.4

Up to date!

Plugins:
  - postgres: 1.0.4 - Up to date!
```

**Comment by emmyoop** [comment]
@jonstacks this makes a lot of sense since we have a set list of types you can define.  Thanks for brining it up and offering a fix.  I'll hop over and check out your PR!
