### ISSUE TITLE
[DAG] Find model in the dag as in the 'LIKE' sql function ('%my_model%')

### ISSUE THREAD

**Issue by llarbodiere** [dbt-labs/dbt-docs#258]
### Describe the feature
We have a LOOOT of model with different sources. 
A cool feature in the DAG under the `--select` category, would be to allow using the `% operator` in the same way of the [LIKE function](https://docs.snowflake.com/en/sql-reference/functions/like.html).
It would allow to not know by hearth the name of each model and be able to find it really fast.

### Describe alternatives you've considered
Having a correct naming convention? (lol)

### Additional context
Not really

### Who will this benefit?
All dbt cloud dag user

### Are you interested in contributing this feature?
Sure ! Let me know how I can help

**Comment by emmyoop** [comment]
This is an interesting idea!  There's an issue for [fuzzier search in the search bar](https://github.com/dbt-labs/dbt-docs/issues/143) but I see you want it specifically in the DAG.  I can see how it would be useful.

We are not actively developing new features in dbt-docs right now but we would be happy to review a PR if you put one together.
