### ISSUE TITLE
[CT-833] Sort dbt docs "Referenced By" and "Depends On" alphabetically

### ISSUE THREAD

**Issue by ian-fahey-dbt** [dbt-labs/dbt-docs#289]
### Describe the feature
Currently, in dbt docs, when you click on the "Depends On" for a particular model, the list of predecessors is not sorted. This makes for a bit of a pothole in flow, as I have frequently looked at the SQL, seen the model I want to jump back to, then clicked one tab over to Depends On and had to scan for the right one. 

### Additional context
I don't believe this is database-specific.

### Who will this benefit?
This is beneficial for users trying to use dbt docs to navigate a project on a research basis. In my example, I was researching for entity resolution work, so I was miles from needing to code anything, which made docs the go-to in my mind. 

### Are you interested in contributing this feature?
I would love to learn how to code this, but it would require that training, as Jerco suggested it was HTML/JS and I have zero experience in those.

**Comment by jtcohen6** [comment]
Thanks for opening @ian-fahey-dbt!

This may require a touch of Angular, which is unfortunate — but if someone knows the magic word here, it should be pretty simple to do:

https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/docs/model.html#L39-L40

And then do the same thing four more times...

https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/docs/source.html#L33

https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/docs/macro.html#L33-L34

https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/docs/snapshot.html#L39-L40

https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/docs/seed.html#L39-L40
