### ISSUE TITLE
[CT-988] Markdown bug in parsing parentheses (round brackets) in URLs

### ISSUE THREAD

**Issue by msat59** [dbt-labs/dbt-docs#300]
### Describe the bug
If parentheses are present in a URL in the markdown file, the first close parenthesis, `)`, is picked as the end of the URL field.

### Steps To Reproduce
I used the code below in an `md` file.
```
{% docs __overview__ %}
# dbt Demo Documentation

Markdown URL parsing bug example is [here](http://msdn.microsoft.com/en-us/library/aa752574(VS.85).aspx)

{% enddocs%}
```

### Expected behavior
The URL parser must pick the last `)` to close the field.

### Screenshots and log output
Below shows how the rest of the URL is ignored (black color at the end)!
![image](https://user-images.githubusercontent.com/20813541/182805323-4ad6d851-726a-4c1d-9a5f-afc99e99731b.png)

And this is the output on the generated document.
![image](https://user-images.githubusercontent.com/20813541/182805517-8cc1b8f1-0500-4baa-a1c8-4d6d1b8af6ba.png)

**The output of `dbt --version`:**
I used `dbt Cloud v1.1.58.17`, but I selected **v1.2 (latest)** to create my Environment.

### Additional context
In order to confirm that it is a bug, I tested the same URL on GitHub and Jupyter Notebook, and they processed it correctly (GitHub parsing: [here](http://msdn.microsoft.com/en-us/library/aa752574(VS.85).aspx))
I tried a few solutions presented on [stackexchange](https://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses), but not of them worked, except using **tinyurl** and **encoding ( to %28 and ) to %29** which are not the best practice.

**Comment by jtcohen6** [comment]
@msat59 Thanks for opening!

I believe we're using [`angular-marked`](https://www.npmjs.com/package/angular-marked) for all Markdown compilation. It also looks like its last publication was... 6 years ago. One more rough edge of `dbt-docs` still being built in the Angular ecosystem (which had its official end of life last year).

FWIW, it does look like Marked is able to handle this URL: [demo](https://marked.js.org/demo/?text=Markdown%20URL%20parsing%20bug%20example%20is%20%5Bhere%5D(http%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Faa752574(VS.85).aspx)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master).

I'm glad you were able to use the URL encoding workaround in the meantime.
