### ISSUE TITLE
[CT-1219] Use `label` instead of `name` for identifying exposures

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-docs#306]
Thanks for this @emmyoop! Sorry I missed your questions the other

As a follow-up to this, let's also start using `label` instead of `name` for identifying exposures in `dbt-docs`, similar to the changes in https://github.com/dbt-labs/dbt-docs/pull/285

_Originally posted by @jtcohen6 in https://github.com/dbt-labs/dbt-core/pull/5844#pullrequestreview-1110405360_

**Comment by jtcohen6** [comment]
*the other day - whoops
