### ISSUE TITLE
[CT-1222] [CT-1220] [Bug] dbt documentation does not list macros that were migrated from dbt-utils

### ISSUE THREAD

**Issue by ali-infostrux** [dbt-labs/dbt-docs#308]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt documentation currently has no mention of the macros that were migrated from dbt-utils in March (https://github.com/dbt-labs/dbt-core/issues/4813) and subsequently released.

For example for date-diff, dbt-utils doc mentions: "DEPRECATED: This macro is now provided in dbt Core. It is no longer available in dbt_utils and backwards compatibility will be removed in a future version of the package."

### Expected Behavior

Having list of macros included in dbt-core and expected behaviour documented like they were in dbt-utils

### Steps To Reproduce

Search for macros in the dbt documentation and find nothing. https://docs.getdbt.com/ 
Search for macros in dbt-utils and see that they are deprecated. https://github.com/dbt-labs/dbt-utils#datediff-source

### Environment

```markdown
dbt 1.2
```

**Comment by jtcohen6** [comment]
Fair! We do have this: https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros

But that page is not automatically updated today. Whereas, if we included them here, they would be

@dbeatty10 Curious if you have a thought here. Relevant to our convo earlier re: the expanded user persona for cross-db macros as utilities / building blocks

**Comment by dbeatty10** [comment]
@jtcohen6 auto-generated documentation for our cross-db macros à la Sphinx docs could be handy for the expanded user persona for cross-db macros as utilities / building blocks.

@ali-infostrux thanks for reaching out about this!

Did you happen to try the search bar in the upper right corner of https://docs.getdbt.com ?

<img width="300" alt="image" src="https://user-images.githubusercontent.com/44704949/191377810-da83fbd7-521b-422d-b65d-f91a2d665e35.png">

When I typed "datediff" I got the following results.  The first four results are all Developer Blog posts, but the next two link to our [list of macros](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros).

<img width="420" alt="image" src="https://user-images.githubusercontent.com/44704949/191377748-5af557b5-b6f6-4b80-a2a2-99383dfe6217.png">

Admittedly, [this page](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros) might be a bit hard to find within the navigation section on the left:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/44704949/191378498-c40eff95-9a6e-4edc-99f0-028cf14390dc.png">

**Comment by jtcohen6** [comment]
> @jtcohen6 auto-generated documentation for our cross-db macros à la Sphinx docs could be handy for the expanded user persona for cross-db macros as utilities / building blocks.

What I was realizing, thanks to this issue, is that we already _have_ auto-generated docs for macros — it's `dbt-docs`! In our codebase, instead of adding docstrings a la Python/Sphinx, we'd need to add `description` + `args`: https://docs.getdbt.com/reference/macro-properties

Bonus points if we could:
- Figure out a way to serve the same structured information (from `manifest.json`) in docs.getdbt.com, to avoid the need to repeat ourselves
- Use Jinja's parser / AST (?) to auto-detect arguments for macros, and record those in the manifest, in case users haven't documented themselves. Sorta relevant: https://github.com/dbt-labs/dbt-core/issues/4999

**Comment by jtcohen6** [comment]
The more immediate question to answer right now: Are there still good reasons to exclude "internal" macros from the `dbt-docs` site?

Especially now that we're adding in utilities that users might _want_ to know about, beyond the internal guts that they should happily ignore.

This caused confusion for at least one user, and I imagine it's done the same for many more.

**Comment by dbeatty10** [comment]
+1 for `dbt-docs` 💪 

I wonder if including "internal" macros for `dbt docs generate` would help make it more discoverable when there is a project macro that is overriding an "internal" macro?
