### ISSUE TITLE
[CT-1228] Incorrect Docs - dbt v1.3 - MODEL/NODE schema correction from `raw_sql` to `raw_code`

### ISSUE THREAD

**Issue by randypitcherii** [dbt-labs/dbt-docs#315]
### Describe the bug
Docs for manifest v6 are not aligned with what dbt v1.3 is producing for me. 

Docs call for a field called `raw_sql` in the `model` jinja var but that field does not exist. It is instead `raw_code` for dbt v1.3

I'd love to fix this, but I haven't been able to figure it out after 20 minutes and now I'm moving on.

Thankss!

**Comment by jtcohen6** [comment]
Thanks @randypitcherii!

Looks like ~we~ I may have missed a spot in https://github.com/dbt-labs/dbt-docs/pull/293:
https://github.com/dbt-labs/dbt-docs/blob/32327aa70c13007a59f065cb79e383623e365122/src/app/docs/operation.js#L30-L33
