### ISSUE TITLE
[CT-1306] Allow "overview" pages for folders

### ISSUE THREAD

**Issue by argemiront** [dbt-labs/dbt-docs#321]
### Describe the feature
`dbt` currently provides documentation pages for the project overview and individual modules. It would be great to have "overview" pages for folders. For example:

```
models
 | - elt_a
 |       |- m1.sql
 |       |- m2.sql
 |       |- elt_a_overview.md
 | - elt_b
 |       |- m3.sql
 |       |- m4.sql
 |       |- elt_b_overview.md
```

By clicking on the folder `elt_a` we would be able to see the overview for the models on that folder.

### Describe alternatives you've considered
Considered linking md files on the webpage, but only models/overview files are converted into html files.

### Additional context
NA

### Who will this benefit?
This would enrich the documentation and data lineage visualization, which is one of the most appreciated dbt features.

### Are you interested in contributing this feature?
Not at this moment, unfortunatelly.

**Comment by lostmygithubaccount** [comment]
@argemiront thanks for opening! I'd go with `README.md` on the naming convention, unless there's some strong reason to use a different one

**Comment by argemiront** [comment]
> @argemiront thanks for opening! I'd go with `README.md` on the naming convention, unless there's some strong reason to use a different one

Hey, @lostmygithubaccount thank you for the feedback! `README.md` looks better to me.

**Comment by SathishJindam** [comment]
I Agree to @argemiront I would suggest we strongly require a Folder level overview. Even our Teams are facing this issue. We are using DBT models widely divided into model folder structure folder consisting specific functionality,incremental model details.
Each model folder used by different team so we need this option to add different overview.md files different model level folders.
 we wanted explain each folder level functionality, speicfy the different models.sql wth incremental strategy,data_size etc in one place.

**Comment by ernestoongaro** [comment]
@MarthaScheffler is this what you're looking for in regards to Macros?

**Comment by argemiront** [comment]
Hey, commenting here to have it reopened
