### ISSUE TITLE
[CT-1379] Revisit DAG default colors

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-docs#325]
### Describe the feature
Let's revisit the default colors on the DAG.  Right now, sql models, python models, exposures, metrics and sources all have different colors.  

### Describe alternatives you've considered
Leaving it as is.

**Comment by jtcohen6** [comment]
Just need to find a friendly designer!

@bossnunta do you know of any good ones? ;)

**Comment by callum-mcdata** [comment]
This is even more relevant because we're proposing adding a new node type in core for `entities`. Not sure what color it should be though and I'm the last person who should be picking colors.
