### ISSUE TITLE
[CT-1448] Designer-designed default color scheme for all DAG nodes

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-docs#337]
### Describe the feature

For Python models, it was requested ([and then contributed by a community member at the Coalesce hackathon!](https://github.com/dbt-labs/dbt-docs/pull/324)) 

I shouldn't be anywhere near deciding on colors for nodes in the DAG, it'd be goofy. designers should come up with something that looks good and is accessible given their expertise in the area. opening this issue for tracking

TODO: enumerate all the things to have default colors for

### Describe alternatives you've considered

N/A

### Additional context

[customer node colors](https://docs.getdbt.com/reference/resource-configs/docs#custom-node-colors) were added in v1.3

### Who will this benefit?

all users of dbt docs. Cloud IDE users in the lineage tab once we reuse the same color scheme there as well

### Are you interested in contributing this feature?

maybe! we can simply follow this PR: https://github.com/dbt-labs/dbt-docs/pull/324

**Comment by jtcohen6** [comment]
@lostmygithubaccount I think we have this already in https://github.com/dbt-labs/dbt-docs/issues/325
