### ISSUE TITLE
[CT-1452] Support mermaid in markdown

### ISSUE THREAD

**Issue by il-dat** [dbt-labs/dbt-docs#338]
### Describe the feature
I have seen many places where [mermaid](https://mermaid-js.github.io/mermaid) can rich the documentation very well.
That's why I've tried to utilize it within dbt project, but it doesn't work yet.

### Additional context
- dbt model doc
- dbt macro doc
- general doc

### Who will this benefit?
- dbt docs site will become richer with mermaid diagrams
- open the door for programmatically generating the diagrams/flows within md files, even use it for building ERD
Sample mermaid for ERD:
```
erDiagram
    CUSTOMER ||--o{ ORDER : places
    CUSTOMER {
        string name
        string custNumber
        string sector
    }
    ORDER ||--|{ LINE-ITEM : contains
    ORDER {
        int orderNumber
        string deliveryAddress
    }
    LINE-ITEM {
        string productCode
        int quantity
        float pricePerUnit
    }
```

**Comment by jtcohen6** [comment]
Agree that this would be cool! It's unlikely something that we'll be prioritizing ourselves in the near future, given our ongoing commitment to `dbt-docs` right now can only be parity + stability. But perhaps as a hackathon project for someone interested??

`dbt-docs` is still written in Angular (!). After a quick search, it looks like there are some resources online for how to integrate the two. Ideal UX here would be the ability to add code blocks with ` ```mermaid `, just like in GitHub Markdown.

We'd need to ensure that this is copacetic from a security standpoint. It looks like there have been some issues in the past (https://security.snyk.io/vuln/SNYK-JS-MERMAID-174698), but also that [the team behind mermaid is serious about resolving these](https://mermaid-js.github.io/mermaid/#/security).

I've also heard some votes in favor of https://github.com/plantuml/plantuml, as a preferable text-to-visual framework for graphs. It [sounds like](https://news.ycombinator.com/item?id=30336672) Mermaid might be easier to write, but PlantUML has been around longer, it's more feature-rich, and it has fewer limitations around the edges.

**Comment by matthieucan** [comment]
I believe this should be reopened, there is a PR adding mermaid.js support for which maintainers' attention would be really appreciated
