### ISSUE TITLE
[CT-1526] View model documentation in new tab from DAG viewer

### ISSUE THREAD

**Issue by BayanHammami** [dbt-labs/dbt-docs#348]
### Describe the feature
At the moment, it is possible to view the model documentation page from the DAG viewer but not in a new tab. This presents a UX issue as users might be exploring the DAG viewer and want to open new tabs for multiple models. This is not possible as the default right click behaviour is no longer available.

![Screenshot 2022-11-17 at 2 33 42 pm](https://user-images.githubusercontent.com/9261317/202585193-9ed28093-f216-48b0-928b-cb1d9fe9a50b.png)

### Describe alternatives you've considered
The browser tab can be duplicated and then one of the DAG viewer tabs can be used to click on the model to view its detailed documentation. This is a poor UX as the user loses track of which section of the DAG they were viewing.

### Additional context
This is a UI feature.

### Who will this benefit?
All users of dbt docs who want to open model documentation in new tabs from the DAG viewer.

### Are you interested in contributing this feature?
Yes

**Comment by jtcohen6** [comment]
Thanks @BayanHammami! From [community slack thread](https://getdbt.slack.com/archives/C2JRTGLLS/p1668656109132979):

> it seems like a 10 line edit in the graphvis.js file if anyone wants to give it a go.

This could be a good contribution opportunity for anyone interested!

**Comment by datadisciple** [comment]
@BayanHammami @jtcohen6 Cool idea - just took a stab at this! (thanks much for the guidance on where to look)
