### ISSUE TITLE
[CT-1840] [Feature] Adding `entities` to dbt-docs

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-docs#360]
### Describe the feature
As we begin to move forward with introducing `entities` into dbt-core, we should ensure that these are properly represented in the dbt-docs.

This is part of the [broader epic around adding `entities`](https://github.com/dbt-labs/dbt-core/issues/6626).

### Additional context
There are outstanding questions around what color this node should be within the graph.

**Comment by emmyoop** [comment]
We may want to add more properties of metrics as part of this work.
