### ISSUE TITLE
[CT-1879] Seeds columns descriptions do not appear in generated docs

### ISSUE THREAD

**Issue by hvassard** [dbt-labs/dbt-docs#361]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

The generated documentation doesn't include the seeds **columns descriptions**, whereas they have been written in a YAML file.
![capture_docs_dbt](https://user-images.githubusercontent.com/55416733/214021121-55f12760-7290-4971-b565-32ef0faf3e24.jpg)

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

I have a dbt project (using Redshift) and I documented my models, snapshots and seeds with YAML files. Here's an example of documentation for a seed, and a snapshot.
![code_seed](https://user-images.githubusercontent.com/55416733/214020217-210b6c59-933c-47e9-a8f0-5ff0bf7e3cf1.jpg)
![code_snapshot](https://user-images.githubusercontent.com/55416733/214020218-bd13f13c-9530-4943-bea1-730b1438b0bc.jpg)

When I do the following commands ...

![bash_docs](https://user-images.githubusercontent.com/55416733/214020394-b5d0b9e3-9a34-4dff-b525-60ed4e46a1f8.png)

... the documentation is generated and served but it doesn't include the description of my seeds columns. This is weird because the tests (that are documented in the same YAML file) are written.

![capture_docs_dbt](https://user-images.githubusercontent.com/55416733/214021121-55f12760-7290-4971-b565-32ef0faf3e24.jpg)

For other snapshots and models it works fine.
![capture_snapshot](https://user-images.githubusercontent.com/55416733/214022140-8cb41729-2de9-47ae-bb7f-159ef1918261.jpg)

When I do a ctrl+F in the generated catalog.json or index.html, the seeds columns descriptions are not found, so I guess the problem is that the docs generated by  `dbt docs generate` doesn't include the seeds columns docs, rather than a UI bug.

### Expected behavior

The documentation should include the seeds columns description.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

Cf "Steps To Reproduce"

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.2
  - latest:    1.3.2 - Up to date!

Plugins:
  - postgres: 1.3.2 - Up to date!
  - redshift: 1.3.0 - Up to date!
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @hvassard ! And thanks for such a thorough write-up and nice screenshots 🤩 

I think your YAML that contains your seed column descriptions says `decription` instead of `description`.

I don't know the backstory, but dbt will allow extra YAML keys, even if it doesn't recognize them. So that's why a key named `decription` can go undetected rather than generating an error.

Wanna try updating that and see if it resolves it?

**Comment by hvassard** [comment]
@dbeatty10 I can't believe that I didn't notice that mistake. I'm sincerely sorry for the disturbance... Thank you so much for your kindness in your response 🙏

**Comment by dbeatty10** [comment]
@hvassard sorry I didn't respond earlier... no problem, and I'm glad it's working for you!
