### ISSUE TITLE
[CT-1980] Welcome message not shown in dbt docs

### ISSUE THREAD

**Issue by halvorlu** [dbt-labs/dbt-docs#366]
### Describe the bug
The overview page of dbt docs shows "(loading)" instead of the welcome message. There is an error in the console: "TypeError: Cannot read properties of undefined (reading 'block_contents')"

### Steps To Reproduce
Run `dbt init`, `dbt docs generate` and `dbt docs serve` with dbt version 1.4.

### Expected behavior
Expected to see the default welcome message on the overview page of dbt docs.

### Screenshots and log output
<img width="649" alt="image" src="https://user-images.githubusercontent.com/6452143/215838226-ad597abf-3229-4657-a275-ecc25a8fbb92.png">

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - bigquery: 1.4.0 - Up to date!
```

**Comment by halvorlu** [comment]
I believe this is due to a new path for `dbt.__overview__` in `manifest.json`, which is now `doc.dbt.__overview__` in dbt 1.4.

**Comment by jtcohen6** [comment]
@halvorlu Thanks for opening, and diagnosing! This should be a quick fix. I opened a corresponding issue in `dbt-core` (https://github.com/dbt-labs/dbt-core/issues/6801) just to track this as a v1.4 regression that we should include in v1.4.x patch release
