### ISSUE TITLE
[CT-2002] Advance markdown not rendering properly

### ISSUE THREAD

**Issue by juls858** [dbt-labs/dbt-docs#368]
### Describe the bug
https://docs.getdbt.com/styles
The styles listed in the docs don't appear to work. I've tested several of them including changeling, collapsible, FAQ, etc.

### Steps To Reproduce
Add any of the example code into `__overview__.md` and  run `generate` and `serve`. The code blocks just render as escaped html.  

### Expected behavior
I would expect the code to behave as described on the webpage and any html elements to be rendered as one would expect in an MD file.

### Screenshots and log output
![image](https://user-images.githubusercontent.com/14811322/216127395-7edba27e-8d3c-400c-bd22-5eb9a0b7e861.png)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**Comment by jtcohen6** [comment]
@juls858 Ah, these are different `docs`!

[These](https://docs.getdbt.com/styles) are reusable styles (React/MDX assets) for the user documentation website (docs.getdbt.com), rather than the dbt feature for auto-generated project documentation (this repo).
