### ISSUE TITLE
[CT-2277] dbt docs show null for database on spark

### ISSUE THREAD

**Issue by mvdwielen** [dbt-labs/dbt-docs#388]
Issue already reported here: https://github.com/dbt-labs/dbt-docs/issues/104

<img width="306" alt="Screen Shot 2020-06-22 at 10 41 57 AM" src="https://user-images.githubusercontent.com/13897643/85300809-0833b080-b475-11ea-8cb5-4639eaf83f8c.png">

Is it the intention to solve this issue in such the name of the project or some other logical value instead of null will be displayed?

**Comment by dbeatty10** [comment]
Thanks for linking back to that original issue @mvdwielen !

A relatively simple code update could be the following suggestion from https://github.com/dbt-labs/dbt-docs/issues/104:
- use the name of the project in place of null values

This isn't something we're able to prioritize anytime soon, but we'd welcome a PR for it! I've labeled this as a `good_first_issue`. 

### Workaround
A workaround in the meantime was suggested [here](https://github.com/dbt-labs/dbt-docs/issues/104#issuecomment-702566420):

> Had the same issue and was pointed in this direction. Not had time to look at the underlying code but a quick fix / workaround is to run the following after generating the documentation:
> 
> ```bash
> sed 's/"database": null/"database": "<DATABASE_NAME>"/g' ./target/manifest.json
> ```

**Comment by jtcohen6** [comment]
With the advent of Unity Catalog in Databricks (and an OSS version in Apache Spark ... someday? maybe?), it's now possible to have a three-level namespace (`catalog` at the top level)
