### ISSUE TITLE
[CT-2278] Package specific overviews are not rendered in 1.4.0 onwards (unless provided at project level)

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-docs#390]
### Describe the bug
Package level overviews from packages imported into a project are not correctly being loaded and rendered in the generated docs sites, instead the default overview is being used. This used to be served on any imported packages. It still works if you copy them to your project level, but this is not standard behaviour. 

### Steps To Reproduce
1. Create a dbt project
2. Create and add the following to `packages.yml`
    ```yml
    packages:
      - package: snowplow/snowplow_web
        version: 0.13.2
    ```
3. Run `dbt deps` then `dbt docs generate` then `dbt docs serve`
4.  Click on the Snowplow_web folder on the left, it will contain the default welcome message
5. Copy the `dbt_packages/snowplow_web/docs/markdown/snowplow_web_overview.md` file to `models/snowplow_web_overview.md` and re-run `dbt docs generate`
6. Refresh the served page (maybe not required), the snowplow web overview is now rendered
7. 
    1. (Optional) Delete the file you added and re-generate and refresh, overview is gone
    2. (Optional) Alternatively, you can delete the specific `doc.<your_project_name>.__snowplow_web__` from the manifest and see the change, note that `doc.snowplow_web.__snowplow_web__` also exists and should be being rendered.

### Expected behavior
The markdown is rendered without needing to copy the file to the project level

### Screenshots and log output

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.4
  - latest:    1.4.4 - Up to date!

Plugins:
  - databricks: 1.4.2 - Up to date!
  - bigquery:   1.4.1 - Up to date!
  - snowflake:  1.4.1 - Up to date!
  - redshift:   1.4.0 - Up to date!
  - postgres:   1.4.4 - Up to date!
  - spark:      1.4.1 - Up to date!
```

### Additional context
Related to https://github.com/dbt-labs/dbt-docs/pull/367/files, my guess is it's related to the following line

https://github.com/dbt-labs/dbt-docs/blob/74bcf9402156745ebed30795d1b69d128c070194/src/app/overview/index.js#L27

which maybe needs to be changed to 
```js
selected_overview = project.docs[`doc.${project_name}.__${project_name}__`] || selected_overview
```

**Comment by dbeatty10** [comment]
Thanks for opening this @rlh1994 !

Your instructions were beautiful and easy to follow. I tried out your suggested fix, and it worked perfectly. I opened up a PR in #391 and gave you co-authorship on it (with you as the first author and me as the second author).
