### ISSUE TITLE
[CT-2285] [CT-2284] [Feature] Searchable metadata on dbt documentation UI

### ISSUE THREAD

**Issue by vmjulio** [dbt-labs/dbt-docs#396]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

An interesting extension of the documentation capability is for users to be able to search for models based on custom metadata.

As of now, the documentation search on the UI can be done by:
- Name
- Description
- Column
- SQL
- Tags

If metadata is embedded directly in the config of a model, on the actual sql file, we can find the results as the search is a text search on the entire sql file content. But, if the meta information is being added on the schema.yml files we are not able to search models that contains them.
As metadata becomes more important for the data assets that are created using dbt, having a way to search them directly on the documentation UI would be a great addition.

**Comment by dbeatty10** [comment]
Thanks for opening @vmjulio !

Is your goal to add content to the `meta` config [similar to the following](https://docs.getdbt.com/reference/resource-configs/meta#designate-a-model-owner) and then be able to search for it?
```yaml
version: 2

models:
  - name: users
    meta:
      owner: "@alice"
      model_maturity: in dev
```

**Comment by dbeatty10** [comment]
We wouldn't be able to prioritize this feature ourselves, but we'd review a PR from a motivated community member.

For prior art, here is the PR that added searching by column descriptions:
- https://github.com/dbt-labs/dbt-docs/pull/371

In particular, this piece shows all the major pieces: https://github.com/dbt-labs/dbt-docs/pull/371/commits/d7f5220e0aabad9fcca320733644e0d956090d78

One thing to note is that the code within `fuzzySearchObj` is a bit of a mish mash of different approaches right now, and it could use some re-factoring.

**Comment by vmjulio** [comment]
I've added this capability through [this PR](https://github.com/dbt-labs/dbt-docs/pull/403).
