### ISSUE TITLE
[CT-2326] Model view: display column-level constraints

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-docs#405]
In the model view (/model/{model_id}) of dbt-docs, display any column-level constraints under the 'Columns' tab. 

Differentiate from generic tests - should specify the `type` of the constraint (not null, unique, etc)

**Comment by jtcohen6** [comment]
Closing as a duplicate of https://github.com/dbt-labs/dbt-docs/issues/433
