### ISSUE TITLE
[CT-2340] Tags in 'Details' view are not wrapped and hence push remaining descriptions out

### ISSUE THREAD

**Issue by florian-scharinger** [dbt-labs/dbt-docs#409]
### Describe the bug
When specifying a list of tags on a model, then the list of tags is shown in a single line, pushing the rest of the documentation out of its designated area. 

### Steps To Reproduce

1) Add tags to a model, e.g. on `schema` level:

        my_schema:
          +schema: my_schema
          +tags:
            - owner_group:group_a
            - owner_group:group_b
            - owner_group:group_c
            - sme:quality:Person A
            - sme:quality:Person B

2) Run `dbt docs-generate`

3) Run `dbt docs-serve`

4) View any of the models/views associated with the tagged schema. 

### Expected behavior

The 'Details' section of a model either wraps the list of tags around or shortens it with `...`. 

### Screenshots and log output

![image](https://user-images.githubusercontent.com/50343561/228646599-81b35ceb-8b83-472e-a213-cc93ded50982.png)

### Additional context

N/A

**Comment by dbeatty10** [comment]
Thanks for opening this issue @florian-scharinger !

What do you think of how this looks?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/44704949/229662413-c9bd1304-a16d-4c6f-8b52-e5cf74cf05db.png">

### Implementation idea
One option is to replace `&nbsp;` with `<br />` here:

https://github.com/dbt-labs/dbt-docs/blob/2bdc46cc474db7ac957b4627db3eb67f34d7e70c/src/app/components/table_details/table_details.html#L20-L22

```html
    <span ng-repeat="tag in model.tags"><code><a ng-click=queryTag(tag)>{{ tag }}</a></code><br /></span>
```

I'm going to label this as a `good_first_issue` for a community member to implement.

**Comment by florian-scharinger** [comment]
Thanks for triaging this issue. Having a vertical list would certainly help readability, but I wonder if it could make this section unnecessary large (vertically) when somebody has a dozen or so tags. An alternative would be to have the tags in a comma-separated list that has a maximum width and the list then wraps within the available space. I had a quick play but couldn't quite get the CSS to work.

**Comment by dbeatty10** [comment]
Sure thing @florian-scharinger 👍 

If you or anyone else can get an improved layout via CSS or other means, open a PR and we'll give it a look.

Here's what I found quickest and easiest to replicate a long list of tags in my local dbt project:

`models/my_model.sql`
```
{{
  config(
    materialized='table',
    tags=[
          "owner_group:group_a",
          "owner_group:group_b",
          "owner_group:group_c",
          "owner_group:group_d",
          "sme:quality:Person A",
          "sme:quality:Person B"
    ],
  )
}}

select 1 as id
```

**Comment by vishalsingh2972** [comment]
can you assign this to me @dbeatty10  want to give it a try!

**Comment by dbeatty10** [comment]
Just assigned this to you @vishalsingh2972
