### ISSUE TITLE
[CT-2397] Resolve versions model clobbering

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-docs#412]
### Describe the bug
When you have versioned models, the collapsed DAG view selects all the models because it selects by name and cannot differentiate between version.

collapsed view
![image](https://user-images.githubusercontent.com/7070049/231276444-e264e73a-319f-4f55-95e9-59bdc1060fd1.png)

expanded view 
![image](https://user-images.githubusercontent.com/7070049/231276465-9699f78b-54f4-435b-b273-f67b1d21b5e3.png)

### Steps To Reproduce
View a model that has multiple versions in the collapsed view.

### Expected behavior
Only the single model with the ~corerct~ correct version is displayed.

### Additional context
See #411 for other version related changes.

**Comment by jtcohen6** [comment]
I believe we ended up fixing this in https://github.com/dbt-labs/dbt-docs/pull/411!
