### ISSUE TITLE
[CT-2678] [Feature] DAG: different color for the model, test and sources failing

### ISSUE THREAD

**Issue by llarbodiere** [dbt-labs/dbt-docs#427]
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/docs/building-a-dbt-project/documentation

### What part(s) of the page would you like to see updated?

Hello,

It would be amazing to be able to see errors directly in the dag:

- Sources: display a different color than green if the freshness test does not pass
- Model runs: display a different color than blue if it fails (suggestion: red)
- Model tests: display a different color than blue if test is failing (maybe light orange) or warning (light yellow)

In order to reduce noise, it would also be great having a Yes/No selector on that to be able to either enable or disable this feature.

### Additional information

If you need help to build it I would love to give an hand. I'm not a software engineer but a motivated analytics engineer :D .

**Comment by jtcohen6** [comment]
This is a very neat idea! It would require reliable access to the (combined) state of recent runs, which we can't really do with `dbt-docs` as currently built (static site fed by JSON artifacts). This is an interesting idea for a future rework of dbt documentation. I'm going to close the issue for now, as outside the reasonable scope of `dbt-docs`.
