### ISSUE TITLE
[CT-2740] Ensure semantic models & metrics are included in DAG viz

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-docs#431]
Minimum viable work to ensure ongoing parity for metrics (old) & semantic models (new):
- dedicated page for each node
- DAG viz

**Comment by emmyoop** [comment]
@jtcohen6 I need to clarify what you're looking for here.  Does it include everything below?  Is the wording what you'd expect?  The screenshots below are all of the existing metrics functionality.

1.  Semantic models get their own heading under Project,`Semantic Models`, same as Metrics have

![Screenshot 2023-08-03 at 4 53 52 PM](https://github.com/dbt-labs/dbt-docs/assets/7070049/c8341f91-3fbe-4cae-9924-907abedbc5de)

2.  Semantic models get their own page with their own url (`http://localhost:8080/#!/semantic_models/...`)

![Screenshot 2023-08-03 at 4 55 21 PM](https://github.com/dbt-labs/dbt-docs/assets/7070049/2aef4e5e-d893-4d2f-8086-38f08841e64c)

3. Represent a semantic model as another part of the DAG, same as metric is distinguished as a node in pink below.

![Screenshot 2023-08-03 at 5 01 28 PM](https://github.com/dbt-labs/dbt-docs/assets/7070049/7444c67b-292a-4b96-a9db-6d140e1f4b76)

5. Be able to select on the semantic model in the DAG
![Screenshot 2023-08-03 at 5 01 07 PM](https://github.com/dbt-labs/dbt-docs/assets/7070049/22b26288-fb98-4939-864e-4f944af975e2)

Anything else?

**Comment by jtcohen6** [comment]
As discussed in Slack, priority order for parity is:
1. DAG viz is still working when you add metrics + semantic models
2. metrics still populate pages with relevant info
3. semantic models have dedicated pages (feels ok to kick this out of scope)
