### ISSUE TITLE
[CT-2833] Make dimension list available on the semantic model documentation page

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/dbt-docs#434]
### Describe the feature
When I open the documentation of a metric, I would like to see the dimensions available for this metric. 

### Describe alternatives you've considered
When scanning through the open issues list, I found [this](https://github.com/dbt-labs/dbt-docs/issues/357) issue about exposing the metric yaml in the documentation. If that was exposed, it would provide the same value. 

### Additional context
When moving to MetricFlow the available dimension list will be extended thanks to additional functionality. However, I'm sure 'dbt compile' actually has to know the available dimension list anyway, so I'm guessing it will not be that much more difficult to make it available in documentation. And considering the MetricFlow functionality, the available dimension list will be even more valuable than in current metrics. 

### Who will this benefit?
When looking for metrics, it is very important to know at which granularities these metrics are available. Let's say I want to calculate country level 'number of orders' metric. I find the 'number of orders' metric in dbt docs, but I still have no idea if I can actually use it to calculate the country level values. 

### Are you interested in contributing this feature?
Sure, but I have no idea where to start.

**Comment by graciegoheen** [comment]
Hello! Thanks for opening up this issue. 

We did some [work for 1.6.1 to include semantic models in the docs site](https://github.com/dbt-labs/dbt-docs/issues/431), would you want dimensions included in the semantic models page?  
<img width="779" alt="Screenshot 2023-08-25 at 11 06 10 AM" src="https://github.com/dbt-labs/dbt-docs/assets/53586774/0dfbe7cc-0106-4ec7-99a4-55881ea7e99e">

I think this would be pretty straightforward to add for the semantic models, but not possible (or would take significant effort) for metrics. 

Candidly, our team isn't able to prioritize new feature development in dbt-docs, so this isn't something we'd be picking up ourselves.

**Comment by siljamardla** [comment]
> would you want dimensions included in the semantic models page?

Absolutely!

**Comment by siljamardla** [comment]
Seems like you already have an idea of how this could be implemented. How can I support?

**Comment by jtcohen6** [comment]
The code to add `dimensions` to the semantic model page would probably be quite similar to the code we already have for displaying `entities`:

https://github.com/dbt-labs/dbt-docs/blob/b8b0dc12f2be9145809414a7cb32b264575b8494/src/app/docs/semantic_model.html#L61-L85

To reiterate Grace above, we won't be able to prioritize this one ourselves - but if you're interested in having a go at it, we'd welcome a PR!

**Comment by SOVALINUX** [comment]
Hi
Linked a PR of a friend of mine that might be useful (or even can be merged). I did solve mine issue with simple visualization, but obviously other attributes might be visualized as well and expand/collapse logic might be added.  
Hope it's helpful
