### ISSUE TITLE
[CT-3031] Footnotes not recognised

### ISSUE THREAD

**Issue by one-data-cookie** [dbt-labs/dbt-docs#448]
### Describe the bug
Using [standard footnote syntax](https://www.markdownguide.org/extended-syntax/#footnotes), i.e. `[^1]` & `[^1]:`, is not recognised. I haven't found anything else to work either. It's puzzling that other extended Markdown syntax, e.g. tables, work but footnotes don't.

### Steps To Reproduce
- Create `*.md` file with doc block
- Add footnote via `[^1]` & `[^1]:`
- `dbt docs generate` & `dbt docs serve`
- Footnotes are not rendered

### Expected behavior
Footnotes to be rendered like this:
![image](https://github.com/dbt-labs/dbt-docs/assets/57877739/0470f2f3-4790-4617-b707-97754451c420)

### Screenshots and log output
```
| column          |
|-----------------|
| some text[^fn1] |

[^fn1]: I don't know.
```

![image](https://github.com/dbt-labs/dbt-docs/assets/57877739/87e912bd-01e5-4632-8761-9cfbc93fe193)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.0
  - latest:    1.6.1 - Update available!
```

**Comment by dbeatty10** [comment]
Thanks for raising this @one-data-cookie 🧠 !

Agreed that footnotes are really handy, and it would be nice if they were supported.

We can't prioritize this ourselves right now, but we'd welcome a PR that adds the ability to render footnotes.

We use the [kramdown-parser-gfm](https://github.com/kramdown/parser-gfm) package which is the parser for [Kramdown](https://github.com/gettalong/kramdown). It looks like Kramdown supports a version of [footnotes](https://kramdown.gettalong.org/syntax.html#footnotes), so it _might_ be possible somehow without drastic changes.

**Comment by one-data-cookie** [comment]
@dbeatty10 Thanks for the reply!

I'd love to help but not sure how to debug this. If I use the same `Gemfile` on a dummy project locally, Kramdown renders it correctly. If, on the other hand, I use `dbt-docs`, it doesn't.

Text:
```md
This is some text.[^1]

[^1]: Works?
```

Local:
```html
<p>This is some text.<sup id="fnref:1" role="doc-noteref"><a href="#fn:1" class="footnote" rel="footnote">1</a></sup></p>

<div class="footnotes" role="doc-endnotes">
  <ol>
    <li id="fn:1" role="doc-endnote">
      <p>Works? <a href="#fnref:1" class="reversefootnote" role="doc-backlink">&#8617;</a></p>
    </li>
  </ol>
</div>
```

![image](https://github.com/dbt-labs/dbt-docs/assets/57877739/578d4e25-6c53-4ac8-aab5-c737e4acbe94)

`dbt-docs`:
![image](https://github.com/dbt-labs/dbt-docs/assets/57877739/8ae90c9f-0621-4c6d-811f-7f5081bb6207)

![image](https://github.com/dbt-labs/dbt-docs/assets/57877739/1094dd6b-193d-4931-8721-0ccad8c25164)
(leading to unknown location "Works?", so basically not recognising this syntax and resulting in an undefined reference)

It looks like something in the code or styles might interfer with it. Alternatively, `dbt-docs` might have a different configuration then I do. Both of these work on my local:
```rb
Kramdown::Document.new(text, input: 'GFM').to_html
Kramdown::Document.new(text).to_html
```

Thoughts or ideas? 🤔

**Comment by one-data-cookie** [comment]
@dbeatty10 Any thoughts or pointers, please? 🙏

**Comment by dbeatty10** [comment]
@one-data-cookie oof, sorry I didn't reply earlier!

[Here's](https://github.com/dbt-labs/dbt-docs#showing-dbt-docs) how you can install and run dbt-docs locally.

The part that is easiest to overlook:
- first copy your `manifest.json` and `catalog.json` files to the `src/` directory

Running dbt-docs locally might help you see what is going on.
