### ISSUE TITLE
[CT-3089] [CT-3065] [Feature] DBT docs allow to view grants for each model

### ISSUE THREAD

**Issue by DanMawdsleyBA** [dbt-labs/dbt-docs#464]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Make it possible to view the different grants on models (Used from the +grants action) in the dbt docs such that I can ensure the grants have been applied correctly across a project.

### Describe alternatives you've considered

Writing a pythn script to look through catalog.json but its not visible.

### Who will this benefit?

Anybody who uses docs to checks model access.

### Are you interested in contributing this feature?

No

**Comment by jtcohen6** [comment]
@DanMawdsleyBA Thanks for opening!

Where would you want to see `grants` appearing in the docs site? On each model's page at the top, inside the [table details](https://github.com/dbt-labs/dbt-docs/blob/b8b0dc12f2be9145809414a7cb32b264575b8494/src/app/components/table_details/table_details.js)?

We're not able to prioritize new additions to `dbt-docs`, but if you or another community member were interested in contributing, you're welcome to open a PR.
