### ISSUE TITLE
[CT-3371] Include unit tests in dbt docs

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-docs#472]
### Describe the feature
- add unit tests to dbt docs
    - listed in the models page (similar to where data tests are listed today)
    - with an accompanying page showing the fixtures being used
- update instances of "tests" to "data tests" when relevant

**Comment by gshank** [comment]
Could you add some specifics to this?  Do you want the unit tests listed in the "Referenced By" tab for the model? 

What does "with an accompanying page showing the fixtures being used" mean?  How would you get to the "accompanying page"? What does it look like?

**Comment by graciegoheen** [comment]
Yes, I think it would be great to add the unit tests listed in the "Referenced By" tab for the model. Something like this:
<img width="314" alt="Screenshot 2024-02-27 at 12 49 15 PM" src="https://github.com/dbt-labs/dbt-docs/assets/53586774/67e9c2bf-85b1-45e6-9592-5a0f61f9ca12">

From there I can click into a page for the data test:
<img width="1020" alt="Screenshot 2024-02-27 at 12 50 52 PM" src="https://github.com/dbt-labs/dbt-docs/assets/53586774/60818fec-babb-4480-8813-691caa149c62">

Would be nice to have some similar page you could click into for the unit test
