### ISSUE TITLE
Docs site does not support unit tests

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-docs#506]
### Describe the bug
Adding a unit test to a project and running the docs site

- does not show a page for the unit test
- breaks the dag

### Steps To Reproduce

1. install dbt-core + adapter >= 1.8.0
2. add a [valid unit test](https://docs.getdbt.com/docs/build/unit-tests) to your project
3. `dbt docs generate && dbt docs serve`

### Expected behavior

1. i see details about the unit test
2. i see a working DAG

### Screenshots and log output

No unit test:

<img width="355" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/73915542/cf41c24d-3847-4f8d-a7ad-ce1dc87127df">

Broken DAG: 

<img width="1415" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/73915542/7678c46f-da9c-4dbb-847d-467382d617a0">

**The output of `dbt --version`:**
<img width="610" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/73915542/7e9618dc-13e8-4d6e-a841-db1db8d9b651">

**Comment by dbeatty10** [comment]
<details>
<summary>

### Reprex
</summary>

`models/my_test_model.sql`

```
select 1 as id
```

`models/_unit.yml`

```
unit_tests:

  - name: my_unit_test
    given: []
    model: my_test_model
    expect:
      rows:
        - {id: 1}
```

```shell
dbt docs generate
dbt docs serve
```

</details>

Here's the error messages I got:

```
(index):79 Can not create edge `c18ac92f-a89a-4bc6-8138-8d53a8dc65e1` with nonexistant target `unit_test.my_project.my_test_model.my_unit_test`
error @ (index):79


(index):79 console.trace
error	@	(index):79
u.restore	@	(index):84
c	@	(index):84
add	@	(index):91
(anonymous)	@	(index):79
$digest	@	(index):73
$apply	@	(index):73
(anonymous)	@	(index):73
A	@	(index):73
b.onload	@	(index):73

(index):73 TypeError: Cannot read properties of undefined (reading 'data')
    at (index):93:333453
    at Module.$t ((index):27:73384)
    at Object.selectNodes ((index):93:333420)
    at Object.selectNodes ((index):93:331596)
    at h ((index):93:324578)
    at p.showFullGraph ((index):93:326710)
    at t.showExpanded ((index):79:27600)
    at t.onLauncherClick ((index):79:28516)
    at fn (eval at compile ((index):47:106042), <anonymous>:4:165)
    at i ((index):73:151833)
(anonymous) @ (index):73
```

<img width="1432" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/44704949/17677d01-b16d-498a-820f-43c8d47d058a">

**Comment by graciegoheen** [comment]
Based on the error, it's possible that we're not populating the catalog appropriately. We had a fix awhile back around re-parsing when a fixture is changed, that could have affected this. It can't find the key and attempts to access an attribute on undefined following that.

This may actually be a fix in dbt-core, not in dbt-docs.
