### ISSUE TITLE
Allow customisation of base path

### ISSUE THREAD

**Issue by Limess** [dbt-labs/dbt-docs#51]
## Current behaviour

When trying to host DBT documentation on a non-top level path the docs site looks for a few files at the root path

e.g.

Hosting the index.html file at https://my-internal-domain.com/dbt 
The docs fail to load due to requesting https://my-internal-domain.com/catalog.json

## Expected behaviour

Allow customisation of the base url so JSON file requests resolve from the given url, e.g https://my-internal-domain.com/dbt/catalog.json.

### Workaround

For now we're fixing this by explicitly proxying `.json` files generated by DBT to the path we expose the dbt documentation on:

```nginx.conf
location ~ ^/(catalog|run_results|manifest)\.json$ {
  rewrite ^/(.*)$ /dbt/$1;
}
```

**Comment by fdroessler** [comment]
Is there any chance something like this could happen?
