### ISSUE TITLE
Search also in SQL

### ISSUE THREAD

**Issue by dubravcik** [dbt-labs/dbt-docs#64]
It would be great if the search searches also in SQL statements and not only in tables and columns, for example when I want to search a particular hardcoded filter in the SQL and I know the keyword. Thanks

**Comment by drewbanin** [comment]
hey @dubravcik - the search functionality used to check in SQL for matches! In practice, it returned a whole lot of junk. If you searched for `orders`, you'd find every model that _referenced_ `orders`, which felt pretty noisy.

Maybe we can just stick the SQL-matches at the bottom of the search results? I think that would be effective for use cases like yours without detracting from name-based searching.

**Comment by dubravcik** [comment]
I see. Following your example, in many scenarios, I would expect that searching `orders` would result in a list including also the models referencing `orders`.  
Your suggestion sounds very useful. Maybe in combination with ability to switch on/off searching in SQL statements would make it perfect.

**Comment by dorzey** [comment]
I might be misunderstanding but isn't this functionality already implemented?

<img width="1014" alt="tmp" src="https://user-images.githubusercontent.com/61307/101999970-0affb780-3cda-11eb-89a8-335497c812a7.png">
