### ISSUE TITLE
How to build custom dbt-docs into a dbt build

### ISSUE THREAD

**Issue by guy-adams** [dbt-labs/dbt-docs#79]
Sorry if I've missed the instructions for this. We are looking again at the lineage styling/colouring piece. However, with the seperation of the dbt and dbt-docs repos, we cannot see how the later builds into the former i.e. how we'd get a version of dbt build from source (or even not built from source, since we don't really need any core dbt changes) to use a custom dbt-docs - could anyone point us in the right direction for this? Thanks!

**Comment by drewbanin** [comment]
hey @guy-adams - we compile this repo to an `index.html` file (using `make dist`) and then copy the compiled `index.html` file into the `core/dbt/include/index.html` file in the dbt Core repo.

If you're looking to make some changes in this repo, I'd recommend:
1. make some changes
2. run `make dist`
3. put the compiled `index.html` file somewhere safe

then later,
1. do a `dbt docs generate`
2. copy your updated `index.html` file into `target/index.html` to clobber the version of `index.html` that ships with dbt Core

**Comment by guy-adams** [comment]
@drewbanin  - perfect, thanks!
