### ISSUE TITLE
Multiple snapshots, same file, missing docs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-docs#95]
Snapshots are missing from the docs if multiple snapshot blocks are defined in the same `snapshots/**.sql` file.

### Steps to replicate

* Define two or more snapshot blocks within a `snapshots/my_snapshot.sql` file
* Generate + view docs. Only the last snapshot block from each file will appear in the docs.
* Move each snapshot blocks into a different `snapshots/**.sql` file
* Generate + view docs. Each snapshot block now appears in the docs.

```
dbt --version
installed version: 0.17.0-rc1
   latest version: 0.16.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.17.0rc1
  - snowflake: 0.17.0rc1
  - redshift: 0.17.0rc1
  - postgres: 0.17.0rc1
```

**Comment by junoha** [comment]
This was never fixed — closed by the stale bot in 2022, no linked PR.

It is easier to hit now: with YAML snapshots (dbt 1.9+), every snapshot in one
YAML file shares the same `original_file_path`, so the project tree keeps only
the last one. Opened #586 with a reproduction and #587 with a fix, which
includes a regression test for the `{% snapshot %}` case reported here.
